### ISSUE TITLE
[BE]Backendアーキテクト検証

### ISSUE THREAD

**Issue by maccostar** [aspidajs/resthub#2]
TypeScriptFriendlyなバックエンドアーキテクト選定をお願いします！

候補
- NEST.JS
- Marble.JS

調査内容
- [x] Databaseの必要有無の調査
1. [AspidaのResasサンプル](https://www.npmjs.com/package/@aspida/resas)を元に平均的なAPIドキュメントのサイズを算出
1. Resthubが管理するAPI数を定義

![IMG_8785](https://user-images.githubusercontent.com/24699538/71557163-a7a75600-2a85-11ea-88bb-c5993595dbb2.JPG)
![IMG_8786](https://user-images.githubusercontent.com/24699538/71557167-ac6c0a00-2a85-11ea-9d8f-dc9ddab8db40.JPG)

- [x] (RDBが必要な場合のみ実施)Postgresのor-mapperの有無

**Comment by shokorep** [comment]
- データベースの要否についての検討
 

1. どんな内容を持たせるか
　①カスタマージャーニー「認知」フェーズの検索内容
　②「検証」「導入」フェーズの型定義されたAPI

2. 何に持たせるか
（a）resthubフロントのプロジェクト内
（b）DB
（c）ファイル


　→(a)だとバックエンドの構築が不要でフロントにリソースを集中できるので(a)で一旦検討する

(a)の場合、データの構成は下図となる想定
![resthubデータ構成](https://user-images.githubusercontent.com/38553438/71568587-dc5df080-2b0b-11ea-85bb-dfe9cf1c39d7.JPG)

①カスタマージャーニー「認知」フェーズの検索内容
　→index.jsonとしてフロントに保持する
②「検証」「導入」フェーズの型定義されたAPI
　→API詳細は詳細表示時にS3から中身のデータを取得して表示

この構成にした場合、一番のボトルネックはindex.jsonとしてフロントに保持できるデータ量となる。
どれくらいのデータ量を保持する必要があるかを以下で検討
　
![resthub検索内容](https://user-images.githubusercontent.com/38553438/71568793-4f1b9b80-2b0d-11ea-9aba-18b06452ecc4.JPG)
![resthub計算](https://user-images.githubusercontent.com/38553438/71568794-5347b900-2b0d-11ea-8167-88f91dc21fd7.JPG)

　→index.jsonとして検索データをフロントに保持する事は可能そう


よって一旦DB不要でフロントのみで行けそうだという結論になりました。
一旦バックエンドのアーキテクチャ選定はpendingもしくはstopで良いでしょうか？？

**Comment by shokorep** [comment]
80×150×2=24,000byte
=24kb
でした。。
失礼しました

**Comment by maccostar** [comment]
調査ありがとうございます〜。
数式や前提があるとレビューしやすくていいですね〜。

結論は変わらない気もしますが、以下の点は、追加で要検討ですかね。
- 例えばGoogleのAPIって音声テキストとか地理とかエンドポイントたくさんあると思うのですが、それはJson上でどのように表現していくのか。(データ形式ってこれで十分なのか。)

- 100〜150社分程度あれば、アーリーアダプターは使いたいと思うのか。
→ボトムアップの積み上げも大事だけど、キャズムを超えることを目的とした場合に、揃えるべきAPI数はこれでいいのだろうか...。

**Comment by shokorep** [comment]
プロモーションにもよると思いますが、
LT一回で１０人がサイトを覗くと仮定して内１人がAPIを登録する
１人が登録するAPIは４〜５個
５個×４人×６月＝１２０個/半年
みたいなロジックでAPI数を出しましたが、
10倍上振れしても250kb程度に収まりそうなので
結論変わらずDBなしでも一旦大丈夫ではと思います！

**Comment by maccostar** [comment]
「結論は変わらない気もしますが」と前置きしたとおり、
やはり結論変わらない見込みが高いので一旦Closeで大丈夫です！

**Comment by shokorep** [comment]
レビューありがとうございます！

- 例えばGoogleのAPIって音声テキストとか地理とかエンドポイントたくさんあると思うのですが、それはJson上でどのように表現していくのか。(データ形式ってこれで十分なのか。)
　googleのAPI全体を検索したい時はOwnerのカラムで検索できる気がしていますが、
　エンドポイントの種別を分けるカラム的なもの、もしくはタグのようなものが必要そうですね。。
　例えば、ユーザーがmapのAPIを使いたい時、
　「google」と検索するのか、
　「map」と検索するのか、
　「位置情報」と検索するのか。
　検索ワードがどうなるかを詰めたいです！
